### ISSUE TITLE
Version 2

### ISSUE THREAD

**Issue by fubarhouse** [fubarhouse/fubarhouse.npm#79]
Some rather advanced testing of #76 has prompted a block of work which changes this role significantly enough to be deemed a major version update - backwards incompatible.

Personally I have found the following problems to be critical enough to stay quiet about and consider them deal-breaking for certain use-cases. I don't know when or how long these items have been problems - however I'm almost at a point where I have a lot of the work done privately and it's simply a matter of completing the work.

The changes include the following:
- [x] #80 Audit of shell exports
- [x] #81 Remove binary linking mechanism
- [x] #82 Version verification should not use absolute path
- [x] #85 Update tests
- [x] #83 Update versions
- [x] Updated deprecated functionality (Ansible)
- [x] Update Jinja2 syntax usage
- [x] #84 Update documentation

**Comment by fubarhouse** [comment]
It's starting to come together, anybody interested can see it under the branch `version-2`

**Comment by fubarhouse** [comment]
So I've been procrastinating too long.

Looking at the latest build on `version-2`, I am unsure if anything more is needed - so I'll go through and check the feature sets. Perhaps a release can come sooner than I expected. :)

**Comment by fubarhouse** [comment]
Coming back to this one over the next two days, I'd like to finish it off.
I'd love feedback if anybody can provide it.

**Comment by fubarhouse** [comment]
Version 2 will now be released, keeping in mind there may be some time until the pipelines complete.
